Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. For a detailed explanation
  # and listing of configuration options, please view the documentation
  # online.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "base"

  config.vm.provisioner = :chef_solo
  config.chef.cookbooks_path = "~/git/swift-solo/chef/cookbooks"
  config.chef.run_list.clear
  config.chef.add_recipe("swift::setup_solo")
  config.chef.add_recipe("swift::setup_functional_tests")

  config.chef.json.merge!({ 
  "swift_servers" => {                                                                            
    "object-server" => {                                                                          
      "6010" => "/srv/1/node",                                                                    
      "6020" => "/srv/2/node",                                                                    
      "6030" => "/srv/3/node",                                                                    
      "6040" => "/srv/4/node"
    },                                                                                           
    "account-server" => {
      "6012" => "/srv/1/node",                                                                    
      "6022" => "/srv/2/node",
      "6032" => "/srv/3/node",                                                                    
      "6042" => "/srv/4/node"                                                                     
    },                                                                                           
    "container-server" => {                                                                       
      "6011" => "/srv/1/node",                                                                    
      "6021" => "/srv/2/node",
      "6031" => "/srv/3/node",                                                                    
      "6041" => "/srv/4/node"
    }
  },
  "rings" => {                                                                                    
    "object" => {                                                                                 
      "z1-127.0.0.1:6010/sdb1" => "1",                                                            
      "z2-127.0.0.1:6020/sdb2" => "1",
      "z3-127.0.0.1:6030/sdb3" => "1",                                                            
      "z4-127.0.0.1:6040/sdb4" => "1"
    },
    "container" => {                                                                              
      "z1-127.0.0.1:6011/sdb1" => "1",                                                            
      "z2-127.0.0.1:6021/sdb2" => "1",                                                            
      "z3-127.0.0.1:6031/sdb3" => "1",                                                            
      "z4-127.0.0.1:6041/sdb4" => "1"                                                             
    },
    "account" => {                                                                                
      "z1-127.0.0.1:6022/sdb1" => "1",
      "z2-127.0.0.1:6022/sdb2" => "1",                                                            
      "z3-127.0.0.1:6022/sdb3" => "1",                                                            
      "z4-127.0.0.1:6022/sdb4" => "1"
    }
  }
  })

end
