Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. For a detailed explanation
  # and listing of configuration options, please view the documentation
  # online.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "base"

  config.vm.provisioner = :chef_solo
  config.chef.cookbooks_path = "~/git/swift-solo/chef/cookbooks"
  config.chef.run_list.clear
  config.chef.add_recipe("swift::default")
  config.chef.add_recipe("swift::functional_tests")
  config.chef.json.merge!({ 
  "swift_servers" => { 
    "object-server" => { 
      "6000" => "/mnt/sdb1/os6000", 
      "6010" => "/mnt/sdb1/os6010", 
      "6020" => "/mnt/sdb1/os6020", 
      "6030" => "/mnt/sdb1/os6030" 
    }, 
    "account-server" => { 
      "6001" => "/mnt/sdb1/as6001", 
      "6011" => "/mnt/sdb1/as6011", 
      "6021" => "/mnt/sdb1/as6021", 
      "6031" => "/mnt/sdb1/as6031" 
    }, 
    "container-server" => { 
      "6002" => "/mnt/sdb1/cs6002", 
      "6012" => "/mnt/sdb1/cs6012", 
      "6022" => "/mnt/sdb1/cs6022", 
      "6032" => "/mnt/sdb1/cs6032" 
    } 
  }, 
  "rings" => { 
    "object" => { 
      "z1-127.0.0.1:6000/foo1" => "1", 
      "z2-127.0.0.1:6010/foo2" => "1", 
      "z3-127.0.0.1:6020/foo3" => "1", 
      "z4-127.0.0.1:6030/foo4" => "1" 
    }, 
    "container" => { 
      "z1-127.0.0.1:6002/foo5" => "1", 
      "z2-127.0.0.1:6012/foo6" => "1", 
      "z3-127.0.0.1:6022/foo7" => "1", 
      "z4-127.0.0.1:6032/foo8" => "1" 
    }, 
    "account" => { 
      "z1-127.0.0.1:6001/foo9" => "1", 
      "z2-127.0.0.1:6011/foo10" => "1", 
      "z3-127.0.0.1:6021/foo11" => "1", 
      "z4-127.0.0.1:6031/foo12" => "1" 
    } 
  }
  })

end
